"use client";
import Link from "next/link";
import dynamic from "next/dynamic";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { searchLocations, submitComplaint, type Complaint, type LocationSearchResult } from "@/lib/api";
const LocationMap = dynamic(() => import("@/components/LocationMap"), { ssr: false });
const categories = [
  ["Pothole / Road Damage","Road","Repair unsafe roads and broken surfaces."],
  ["Garbage Overflow","Garbage","Report waste collection and overflow issues."],
  ["Water Leakage","Water","Flag leaks, flooding, and water access problems."],
  ["Broken Street Light","Electricity","Highlight dark or unsafe public spaces."],
  ["Public Transport Issue","Public Transport","Share service and access problems."],
  ["Safety / Security","Safety","Raise a public safety concern."],
  ["Drainage Problem","Drainage","Report blocked drains and waterlogging."],
  ["Other","Other","Tell us about another civic issue."],
] as const;
export default function ReportPage(){
 const [selected,setSelected]=useState<string[]>([]);
 const [description,setDescription]=useState("");
 const [files,setFiles]=useState<Record<string,File|null>>({});
 const [query,setQuery]=useState("");
 const [results,setResults]=useState<LocationSearchResult[]>([]);
 const [location,setLocation]=useState<LocationSearchResult|null>(null);
 const [searching,setSearching]=useState(false);
 const [error,setError]=useState("");
 const [loading,setLoading]=useState(false);
 const [created,setCreated]=useState<Complaint[]>([]);
 useEffect(()=>{const q=query.trim();if(q.length<2||location?.display_name===q){setResults([]);return}const controller=new AbortController();const timer=window.setTimeout(async()=>{setSearching(true);try{setResults(await searchLocations(q,controller.signal))}catch{if(!controller.signal.aborted)setResults([])}finally{if(!controller.signal.aborted)setSearching(false)}},400);return()=>{window.clearTimeout(timer);controller.abort()}},[query,location]);
 const markers=useMemo(()=>location?[{id:"pin",latitude:location.latitude,longitude:location.longitude,label:location.display_name}]:[],[location]);
 function toggle(category:string){setSelected(v=>v.includes(category)?v.filter(x=>x!==category):[...v,category]);}
 function pin(lat:number,lon:number){const p={display_name:`Pinned location (${lat.toFixed(5)}, ${lon.toFixed(5)})`,latitude:lat,longitude:lon};setLocation(p);setQuery(p.display_name);setResults([]);}
 async function submit(e:FormEvent){e.preventDefault();setError("");setCreated([]);if(!selected.length){setError("Select at least one issue category.");return}if(!location){setError("Search for an address or place a pin on the map.");return}if(!description.trim()){setError("Describe the issue before submitting.");return}setLoading(true);const saved:Complaint[]=[];try{for(const choice of selected){const entry=categories.find(x=>x[0]===choice)!;const result=await submitComplaint({text:`Issue category: ${entry[1]}. ${description.trim()}`,latitude:location.latitude,longitude:location.longitude,formatted_address:location.display_name,file:files[choice]});saved.push(result);setCreated([...saved]);}}catch(reason){setError(reason instanceof Error?reason.message:"Could not submit every selected issue.");}finally{setLoading(false)}}
 return <div className="civic-grain"><div className="mx-auto grid max-w-7xl items-start gap-10 px-5 py-12 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><section className="pt-2"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#117d78]">Citizen voice / policy insight</p><h1 className="mt-4 text-4xl font-bold leading-tight text-[#12243a] sm:text-6xl">Report an issue in your neighbourhood.</h1><p className="mt-5 max-w-xl leading-7 text-slate-600">Choose every issue you want to report. Each selected category becomes its own traceable report at the pinned location.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/track" className="rounded-full bg-[#12243a] px-5 py-3 text-sm font-bold text-white hover:bg-[#117d78]">Track an existing report</Link><span className="rounded-full border border-[#e4dfd3] bg-white px-5 py-3 text-sm text-slate-600">No account required</span></div></section>
 <section className="rounded-[2rem] border border-[#e4dfd3] bg-white p-6 shadow-soft sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#117d78]">New submission</p><h2 className="mt-2 text-2xl font-bold text-[#12243a]">Describe what needs attention</h2><form onSubmit={submit} className="mt-6 space-y-6"><fieldset><legend className="mb-3 text-sm font-bold text-[#12243a]">Select one or more issue categories</legend><div className="grid gap-3 sm:grid-cols-2">{categories.map(([label,value,copy])=>{const active=selected.includes(label);return <div key={label} className={`rounded-2xl border p-4 transition ${active?"border-[#117d78] bg-[#eef6f3] shadow-[0_0_0_3px_rgba(17,125,120,.08)]":"border-[#e4dfd3] bg-[#fbfaf7] hover:border-[#c49a42]"}`}><button type="button" aria-pressed={active} onClick={()=>toggle(label)} className="flex w-full items-center justify-between text-left"><span className="text-sm font-bold text-[#12243a]">{label}</span><span className={`grid h-5 w-5 place-items-center rounded-full text-xs ${active?"bg-[#117d78] text-white":"border border-slate-300"}`}>{active?"✓":""}</span></button><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p>{active&&<label className="mt-3 block text-xs font-semibold text-[#117d78]">Add a photo for this issue (optional)<input type="file" accept="image/*" onChange={e=>setFiles(v=>({...v,[label]:e.target.files?.[0]??null}))} className="mt-2 block w-full text-xs text-slate-500 file:mr-3 file:rounded-full file:border-0 file:bg-white file:px-3 file:py-2 file:font-bold file:text-[#117d78]"/></label>}</div>})}</div></fieldset>
 <div><label htmlFor="description" className="mb-2 block text-sm font-bold text-[#12243a]">Issue details</label><textarea id="description" required rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe what happened, when it started, and who is affected..." className="w-full resize-y rounded-2xl border border-[#e4dfd3] bg-[#f7f5f0] px-4 py-3 text-sm leading-6 outline-none focus:border-[#117d78]"/></div>
 <div><label htmlFor="place" className="mb-2 block text-sm font-bold text-[#12243a]">Pin the location <span className="font-normal text-slate-400">(required)</span></label><input id="place" value={query} onChange={e=>{setQuery(e.target.value);setLocation(null)}} onKeyDown={e=>{if(e.key==="Enter"&&results[0]){e.preventDefault();setLocation(results[0]);setQuery(results[0].display_name);setResults([])}}} placeholder="Search an address or area" autoComplete="off" className="h-12 w-full rounded-xl border border-[#e4dfd3] bg-[#f7f5f0] px-4 text-sm outline-none focus:border-[#117d78]"/>{(searching||results.length>0)&&!location&&<div className="mt-2 overflow-hidden rounded-xl border border-[#e4dfd3] bg-white">{searching&&<p className="p-3 text-sm text-slate-500">Searching...</p>}{results.map(r=><button type="button" key={r.display_name} onClick={()=>{setLocation(r);setQuery(r.display_name);setResults([])}} className="block w-full border-b p-3 text-left text-xs hover:bg-[#eef6f3]">{r.display_name}</button>)}</div>}<p className="mt-2 text-xs text-slate-500">Choose a search result or click the map to place a pin.</p><div className="mt-3"><LocationMap markers={markers} height={260} onMapClick={pin} openPopupMarkerId="pin"/></div></div>
 {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-2xl bg-[#117d78] px-5 py-4 text-sm font-bold text-white hover:bg-[#12243a] disabled:opacity-50">{loading?"Submitting selected reports...":`Submit ${selected.length||""} report${selected.length===1?"":"s"} →`}</button></form>{created.length>0&&<div role="status" className="mt-6 rounded-2xl border border-[#117d78]/20 bg-[#eef6f3] p-5"><p className="font-bold text-[#117d78]">Submitted {created.length} report{created.length===1?"":"s"} successfully.</p><p className="mt-2 text-sm text-slate-600">Keep these IDs to track each report:</p><div className="mt-3 flex flex-wrap gap-2">{created.map(c=><Link key={c.id} href={`/track?id=${c.id}`} className="rounded-full bg-white px-3 py-2 text-xs font-bold text-[#117d78]">#{c.id}</Link>)}</div></div>}</section></div></div>;
}